### ISSUE TITLE
mysql-async Taking 0.05ms and having Hitch Warnings :)

### ISSUE THREAD

**Issue by Tinky124** [brouznouf/fivem-mysql-async#113]

**Comment by foregz** [comment]
got it fixed ?

**Comment by Local9** [comment]
0.05ms is very very fast and should be fine, if that is query response time for a single row then I'd be looking at how your tables are made and if they are indexed or not.

Hitch warnings can be caused by any number of things on a system, they are rather hard to pin point from my experience but I believe some one else may have better input.
