### ISSUE TITLE
Can't connect to remote DataBase

### ISSUE THREAD

**Issue by blaizzmc** [brouznouf/fivem-mysql-async#38]
Hi i'm currently using the latest version on Windows.

I'm trying to connect to this [database](http://164.132.203.113:8080/phpmyadmin/index.php) but I can't. I'm 100% sure about the password and username because I can connect manualy, so I guess I used the connection string wrong

`set mysql_connection_string "mysql://USER:PASSWORD@164.132.203.113/TABLE?dateStrings=true"`
Gives the following :

> Access denied for user 'USER'@'MYIP' (using password yes)

**Comment by geekwithbadge** [comment]
I second this issue. I had to go back to the last version.

**Comment by GHMatti** [comment]
I cannot replicate (using MariaDB 10.3). I set up a remote database on a different pc in my local network. By the following usual steps:

* Comment out the `bind-address` in the `my.ini` / `my.cnf`
* Add a user with database privileges for my origin ip address, e.g. if done badly `grant all privileges on test.* for 'remotetest'@'<my origin ip>' identifed by 'password';
* restarted mysql.

And it worked. No issues at all.

Instead of the origin ip you can use `%` to allow any ip.

**Comment by vecchiotom** [comment]
🤔

**Comment by TayHD** [comment]
I also have this issue as well.

**Comment by GHMatti** [comment]
Thank you for telling me how to reproduce this `issue` so I can fix it. Instead of telling me randomly there is a issue.

Because I do not have that issue. You can try the insecureAuth option, which I would not recommend, and instead setting up your database properly.

**Comment by FrazzIe** [comment]
I also have this issue, help.

**Comment by vecchiotom** [comment]
i also have this issue as well, please feex or me no pay fivem.

**Comment by mitchal01** [comment]
This is not an issue with your code this is an issue with MySQL, So a lot of people use xampp for a MySQL database and that what I planed to use. I had tried it stand alone so straight a MySQL server and it worked fine as wine. So I started thinking why is it giving this error, I look and fivem wanted to use hostnames instead of an IP. So I looked for a resolved and Like it was stated in this repo before me I put my bind address as 0.0.0.0 so it wouldn't just look for one, when I the ip of the computer it broke it even more. Now that the bind address is 0.0.0.0 and I'm using xampp It works fine for me.

**Comment by GHMatti** [comment]
>  So a lot of people use xampp for a MySQL database.
Really why? Not like MariaDB packs heidisql (optional for years now) and has the bind to 0.0.0.0 by default.
Why do people install big black boxes with potentially more security flaws than an installation by hand? Which contains additional packages that are not even needed.

Thanks. Good to know should teach people not relying on xampp.

**Comment by mitchal01** [comment]
@GHMatti  It is apparently what most collages are using, one because it has a web server, a MySQL server, FTP server, mail server, and tomcat what ever it is I use four out of the five

**Comment by GHMatti** [comment]
No reproduction found. Closed.
